spring:
  application:
    name: ai-music-backend
  devtools:
    restart:
      enabled: true
    livereload:
      port: 55729
  profiles:
    active: dev

app:
  stream:
    key: "generation-tasks-stream"
    consumer-group: "music-generation-group"
    consumer-name: "consumer-1"

# ====================================================
# =               General Configuration              =
# ====================================================
server:
  port: 8080
  servlet:
    context-path: /dev-api

# MyBatis-Plus Configuration
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration: # MyBatis raw configuration
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# MinIO Configuration

# Logging Configuration
logging:
  level:
    root: info # global logging level
    org.demo.aimusic: debug # specific package logging level
    org.springframework.web: info
    org.springframework.security: info
    com.baomidou.mybatisplus: debug
